### ISSUE TITLE
no optimizations made

### ISSUE THREAD

**Issue by macgyver** [ben-eb/cssnano-cli#6]
Sorry if I'm making an obvious mistake, but can you point out what I'm doing wrong? I tried to use cssnano for autoprefixer and rule compacting, but all it seems to be doing is removing whitespace

```
$ cat dist/css/test.css
div {
	margin: 0;
	margin: 1rem;
	appearance: none;
}
$ cssnano dist/css/test.css dist/css/test.min.css
$ cat dist/css/test.min.css
div{margin:0;margin:1rem;appearance:none}
```

I expected it to look like this:
```
div{margin:1rem;-webkit-appearance:none;-moz-appearance:none;appearance:none;}
```

**Comment by ben-eb** [comment]
You're not doing anything wrong; no prefixes are added as autoprefixer is used in a removal only capacity; this is a compression tool. See http://cssnano.co/optimisations/#autoprefixer. 😄 

Secondly, we don't support declaration merging yet; there is an open issue for it. https://github.com/ben-eb/cssnano/issues/86
